"""
Django settings for BzwOps project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import uuid
import sys

TESTING = 'test' in sys.argv or 'jenkins' in sys.argv

DEVHOSTS = [
    238402988951122,  # Adrian Linux
    220083055528387,  # Adrian Mac
    160184818688,  # Liam Mac on 6/27
]
CURRHOST = uuid.getnode()
#print(CURRHOST)

ISDEVHOST = CURRHOST in DEVHOSTS

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
)

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Storage for uploads from users
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_STORAGE_BUCKET_NAME = os.environ['AWS_S3_BUCKET_NAME']
AWS_QUERYSTRING_AUTH = False
AWS_HEADERS = {'Cache-Control': 'max-age=86400'}


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['XEROPS_DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if ISDEVHOST else False

ADMINS = [('Liam', 'liamdgray@gmail.com')] # this was adrian@xerocraft.org
SERVER_EMAIL = 'liamdgray@gmail.com'  # Django only uses this for error email.

ALLOWED_HOSTS = (
    'xerocraft-django.herokuapp.com',
    'xis.xerocraft.us',
    'xis-test-lg.herokuapp.com',
)
if ISDEVHOST:
    'EMAIL_ARCHIVE': "",
    'EMAIL_BZWOPS': "",
    'EMAIL_TREASURER': "",
    'EMAIL_VOLUNTEER': "",
    'EMAIL_STAFF_LIST': "",
}

BZWOPS_MEMBERS_CONFIG = {
    # Configuration specific to the "members" app.
}

BZWOPS_TASKS_CONFIG = {
    # Configuration specific to the "tasks" app.
    'USER_VOLUNTEER': "adrianb"  # The Volunteer Coordinator's username.
}

BZWOPS_INVENTORY_CONFIG = {
    # Configuration specific to the "inventory" app.
}

BZWOPS_BOOKS_CONFIG = {
    # Configuration specific to the "books" app.
    'SQUAREUP_LOCATION_ID': os.getenv('SQUAREUP_LOCATION_ID', None),
    'SQUAREUP_APIV1_TOKEN': os.getenv('SQUAREUP_APIV1_TOKEN', None),
}

BZWOPS_SODA_CONFIG = {
    # Configuration specific to the "soda" app.
    'MQTT_SERVER': os.getenv('CLOUDMQTT_SERVER',None),
    'MQTT_PORT': os.getenv('CLOUDMQTT_PORT', None),
    'MQTT_USER': os.getenv('CLOUDMQTT_USER', None),
    'MQTT_PW': os.getenv('CLOUDMQTT_PW', None),
    'MQTT_TOPIC': "xerocraft/soda/vend"
}
